/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.application;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.MediaTracker;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

/**
 *
 * @author Michal
 */
public class FacultyFrame extends javax.swing.JFrame {

    MsgDialog msgDlg = new MsgDialog(new javax.swing.JFrame(), true);

    /**
     * Creates new form FacultyFrame
     */
    public FacultyFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbQueryMethod.addItem("Runtime Object Method");
        cbQueryMethod.addItem("Java execute() Method");
        cbFacultyName.addItem("Nilesh Jogoo");
        cbFacultyName.addItem("Satish Bhalla");
        cbFacultyName.addItem("Black Anderson");
        cbFacultyName.addItem("Brett Freeman");
        cbFacultyName.addItem("Jenney King");
        cbFacultyName.addItem("Henry Averies");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFacultyName = new javax.swing.JPanel();
        lblFacultyName = new javax.swing.JLabel();
        lblQueryMethod = new javax.swing.JLabel();
        cbFacultyName = new javax.swing.JComboBox<>();
        cbQueryMethod = new javax.swing.JComboBox<>();
        pFacultyInfo = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblOffice = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblCollege = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtOffice = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtCollege = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSelect = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        ImageCanvas = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CSE DEPT Faculty Form");

        pFacultyName.setBorder(javax.swing.BorderFactory.createTitledBorder("Faculty Name and Query Method"));

        lblFacultyName.setText("Faculty Name");

        lblQueryMethod.setText("Query Method");

        javax.swing.GroupLayout pFacultyNameLayout = new javax.swing.GroupLayout(pFacultyName);
        pFacultyName.setLayout(pFacultyNameLayout);
        pFacultyNameLayout.setHorizontalGroup(
            pFacultyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFacultyNameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pFacultyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQueryMethod)
                    .addComponent(lblFacultyName))
                .addGap(41, 41, 41)
                .addGroup(pFacultyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbFacultyName, 0, 250, Short.MAX_VALUE)
                    .addComponent(cbQueryMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pFacultyNameLayout.setVerticalGroup(
            pFacultyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFacultyNameLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pFacultyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyName)
                    .addComponent(cbFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pFacultyNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQueryMethod)
                    .addComponent(cbQueryMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pFacultyInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Faculty Information"));

        lblTitle.setText("Title");
        lblTitle.setToolTipText("");

        lblOffice.setText("Office");

        lblPhone.setText("Phone");

        lblCollege.setText("College");

        lblEmail.setText("Email");

        javax.swing.GroupLayout pFacultyInfoLayout = new javax.swing.GroupLayout(pFacultyInfo);
        pFacultyInfo.setLayout(pFacultyInfoLayout);
        pFacultyInfoLayout.setHorizontalGroup(
            pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFacultyInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOffice)
                    .addComponent(lblPhone)
                    .addComponent(lblCollege)
                    .addComponent(lblTitle)
                    .addComponent(lblEmail))
                .addGap(35, 35, 35)
                .addGroup(pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCollege)
                    .addComponent(txtEmail)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOffice)
                    .addComponent(txtPhone))
                .addGap(75, 75, 75))
        );
        pFacultyInfoLayout.setVerticalGroup(
            pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFacultyInfoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOffice)
                    .addComponent(txtOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCollege)
                    .addComponent(txtCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFacultyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnInsert.setText("Insert");

        btnUpdate.setText("Update");

        btnDelete.setText("Delete");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        ImageCanvas.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImageCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pFacultyInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pFacultyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pFacultyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ImageCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnSelect)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnBack))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed

        javax.swing.JTextField[] f_field = {txtTitle, txtOffice, txtPhone, txtCollege, txtEmail};

        String query = "SELECT title, office, phone, college, email " + "FROM Faculty WHERE faculty_name = ?";
        if (cbQueryMethod.getSelectedItem() == "Runtime Object Method") {
            try {
                DatabaseMetaData dbmd = LoginFrame.conn.getMetaData();
                String drName = dbmd.getDriverName();
                String drVersion = dbmd.getDriverVersion();
                msgDlg.setMessage("DriverName is: " + drName + ", Version is: " + drVersion);
                msgDlg.setVisible(true);

                PreparedStatement pstmt = LoginFrame.conn.prepareStatement(query);
                pstmt.setString(1, cbFacultyName.getSelectedItem().toString());
                ResultSet rs = pstmt.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                msgDlg.setMessage("Faculty Table has " + rsmd.getColumnCount() + " Columns");
                msgDlg.setVisible(true);

                while (rs.next()) {
                    for (int i = 1; i <= rsmd.getColumnCount(); i++) {
                        f_field[i - 1].setText(rs.getString(i));
                    }
                }

                if (!ShowFaculty()) {
                    msgDlg.setMessage("No matched faculty image found!");
                    msgDlg.setVisible(true);
                }
                
            } catch (SQLException e) {
                msgDlg.setMessage("Error in statement! " + e.getMessage());
                msgDlg.setVisible(true);
            }

        } else if (cbQueryMethod.getSelectedItem() == "Java execute() Method") {
            try {
                PreparedStatement pstmt = LoginFrame.conn.prepareStatement(query);
                pstmt.setString(1, cbFacultyName.getSelectedItem().toString());

                ResultSet rs = pstmt.executeQuery();
                while (rs.next()) {
                    for (int i = 1; i <= 5; i++) {
                        f_field[i - 1].setText(rs.getString(i));
                    }
                }
            } catch (SQLException e) {
                msgDlg.setMessage("Error in statement! " + e.getMessage());
                msgDlg.setVisible(true);

            }

        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private boolean ShowFaculty() {
        Image img;
        int imgId = 1, maxNumber = 5, timeout = 1000;
        MediaTracker tracker = new MediaTracker(this);

        String fImage = null;
        String[] fname = {"Nilesh Jogoo", "Satish Bhalla", "Black Anderson", "Brett Freeman", "Jenney King", "Henry Averies"};

        String[] fimage = {"Jogoo.jpg", "Bhalla.jpg", "Anderson.jpg", "Freeman.jpg", "King.jpg", "Averies.jpg"};

        for (int i = 0; i <= maxNumber; i++) {
            if (fname[i].equals((String) cbFacultyName.getSelectedItem())) {
                fImage = fimage[i];
                break;
            }
        }
        if (fImage != null) {
            img = this.getToolkit().getImage(fImage);
            Graphics g = ImageCanvas.getGraphics();
            tracker.addImage(img, imgId);
            try {
                if (!tracker.waitForID(imgId, timeout)) {
                    msgDlg.setMessage("Faled to load image!");
                    msgDlg.setVisible(true);
                }
            } catch (InterruptedException e) {
                msgDlg.setMessage(e.toString());
                msgDlg.setVisible(true);
            }
            g.drawImage(img, 0, 0, ImageCanvas.getWidth(), ImageCanvas.getHeight(), this);
            return true;

        } else {
            return false;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas ImageCanvas;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbFacultyName;
    private javax.swing.JComboBox<String> cbQueryMethod;
    private javax.swing.JLabel lblCollege;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacultyName;
    private javax.swing.JLabel lblOffice;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblQueryMethod;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pFacultyInfo;
    private javax.swing.JPanel pFacultyName;
    private javax.swing.JTextField txtCollege;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOffice;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
